### ISSUE TITLE
spring-boot-starter-data-mongodb-reactive how to limit data

### ISSUE THREAD

**Issue by knockinHeavenDoor** [hantsy/spring-reactive-sample#1]
I have a problem that is when i using spring-boot-starter-data-mongodb-reactive and it is a lot of data,
but i can't return all data beacuse of too much.At this moment,i must be using limit,but i don't know how to limit,can you tell me or show me demo ? thanks!

**Comment by hantsy** [comment]
Check the docs of Reactor.
 
https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html

`prefetch` is provied in reactor 3.0 and in 3.1 there are some methods archived this purpose, eg. `skip` and `limitRate`

**Comment by hantsy** [comment]
@knockinHeavenDoor Spring Data Mongo reactive support `Pageable` as one of the method parameter in query execution as the original way, but it can only return a `Flux` instead of  a `Page` result.

For simple pagination, use Flux `take` and `skip` directly.

**Comment by hantsy** [comment]
@knockinHeavenDoor  Added [pageable sample](https://github.com/hantsy/spring-reactive-sample/tree/master/data-mongo-pageable).

**Comment by niksw7** [comment]
Since this is related to limit, is this functionality a bug in reactor-core:3.2.1.RELEASE?
```
Flux.range(1,1000).log()
            .limitRate(100,3)
            .subscribe()
```

This is the output returned.  I was expecting request(3) to come post the fetch of 100 elements.
```
08:46:08.627 [main] INFO reactor.Flux.Range.1 - | request(100)
08:46:08.628 [main] INFO reactor.Flux.Range.1 - | onNext(1)
08:46:08.628 [main] INFO reactor.Flux.Range.1 - | onNext(2)
08:46:08.628 [main] INFO reactor.Flux.Range.1 - | onNext(3)
08:46:08.628 [main] INFO reactor.Flux.Range.1 - | request(3)
08:46:08.628 [main] INFO reactor.Flux.Range.1 - | onNext(4)
08:46:08.628 [main] INFO reactor.Flux.Range.1 - | onNext(5)
08:46:08.628 [main] INFO reactor.Flux.Range.1 - | onNext(6)
08:46:08.628 [main] INFO reactor.Flux.Range.1 - | request(3)
08:46:08.629 [main] INFO reactor.Flux.Range.1 - | onNext(7)
08:46:08.629 [main] INFO reactor.Flux.Range.1 - | onNext(8)
08:46:08.629 [main] INFO reactor.Flux.Range.1 - | onNext(9)
```
