### ISSUE TITLE
Request for WebFilter example that validates the request body

### ISSUE THREAD

**Issue by Isaacwhyuenac** [hantsy/spring-reactive-sample#1112]
Hi. Do you have guideline on how to use WebFilter to validate a custom request body??

For example,

The server is receiving the following body like

```js
{
// Other key value pair
  "persons": [
    {
      "firstname": "",
      "lastname": "",
      "ID": ""
    }
  ],
// Other key value pair
}
```

The `ID` field has to send to another server for validation and if one of the person's IDs is invalid, we stop proceeding with the whole request. I want to use Webfilter to decouple this business logic from the main logic. How can I do it??

**Comment by hantsy** [comment]
@Isaacwhyuenac If it as a payload to send other servers, it is better to do validation before sending.

```java

@Inject Validator validator;

...

val constraints = validator.validate(payloadObject);// payloadObjects use Validation annotations to validate the nested objects.



```

**Comment by Isaacwhyuenac** [comment]
Hi Hantsy. Thx for your reply.

The server I mention is tasked with doing identity validation. If I send ID to that server, it will tell me if it is blacklisted and if the customer is always unwelcome. If I use WebFilter to complete task, how can I convert the request body from Webflux to Pojo??

Regards,
Isaac
