### ISSUE TITLE
java9 branch ,publisher,reponse  timeout 

### ISSUE THREAD

**Issue by shengxiaoyuan** [hantsy/spring-reactive-sample#14]
In the Java9  section , when i run the  ApplicationTests  ,the test result is error , so with the picture 

![QzpcVXNlcnNcemhpeXVhbi53YW5nXEFwcERhdGFcUm9hbWluZ1xEaW5nVGFsa1w1NzYwNTExOF92MlxJbWFnZUZpbGVzXDI3NjA5NDFcMTU2MjcyNzAxNTEyN180MzY1MUM5Qy01Nzc1LTRhZGMtQTU1NS0zNjZFMjIyOUNBODQucG5n](https://user-images.githubusercontent.com/11643895/60937087-d6781700-a301-11e9-8081-968a76a62808.png)

 And the code follows:
`@RestController
@RequestMapping(value = "/posts")
public class PostController {

    @GetMapping
    public Flow.Publisher<Post> all() {
        SubmissionPublisher publisher = new SubmissionPublisher();
        publisher.submit(new Post(1L, "post one", "content of post one"));
        publisher.submit(new Post(2L, "post two", "content of post two"));

        return publisher;
    }

}`

But when i  modify the the code as  the below ,the response id correct:

`@RestController
@RequestMapping(value = "/posts")
public class PostController {

    @GetMapping
    public Flow.Publisher<Post> all() {
       return JdkFlowAdapter.publisherToFlowPublisher(Flux.just(new Post(2L, "post two", "content of post two")));
    }
}`

**Comment by hantsy** [comment]
Great point.

I also encountered this issue and posted it on stackoverflow before, and I also got the similar suggestions as you commented. 

In this sample, I only want to use **pure** Flow(Reactive) API to build a publisher, but current code(only use Java 9 Flow API) seems does not work as expected.

**Comment by shengxiaoyuan** [comment]
> Great point.
> 
> I also encountered this issue and posted it on stackoverflow before, and I also got the similar suggestions as you commented.
> 
> In this sample, I only want to use **pure** Flow(Reactive) API to build a publisher, but current code(only use Java 9 Flow API) seems does not work as expected.

thx!!!

**Comment by hantsy** [comment]
close via https://github.com/hantsy/spring-reactive-sample/commit/bf9a4e07e283cbdcdf7df7707f96cf57f5f3c5a7
