### ISSUE TITLE
Why don't you use StepVerifier?

### ISSUE THREAD

**Issue by driversti** [hantsy/spring-reactive-sample#16]
As is in the title. I believe you could use the StepVerifier [here](https://github.com/hantsy/spring-reactive-sample/blob/master/boot-data-mongo/src/test/java/com/example/demo/PostRepositoryTest.java#L49) instead of `block()`. Correct me if I'm wrong, please :)

**Comment by hantsy** [comment]
See other tests in the same classes, this test just demo block is working well.

**Comment by driversti** [comment]
> See other tests in the same classes, this test just demo block is working well.

Yes, I've seen them. That's why I was curious why have you used a blocking approach in this case
