### ISSUE TITLE
Incorrect link in the article

### ISSUE THREAD

**Issue by IncompletableFuture** [hantsy/spring-reactive-sample#168]
Hi! 

I was reading one of your articles and found a small mistake. I see you've merged package *boot-data-mongo-auditing* with *boot-data-mongo*, but now link in the article isn't correct. Here is an anchor where incorrect link is located:

https://hantsy.github.io/spring-reactive-sample/data/data-mongo.html#data-auditing-support

<img width="703" alt="image" src="https://user-images.githubusercontent.com/39883818/141999610-2e0b498c-9f88-4dd6-a49c-0c1dad729cef.png">

**Comment by hantsy** [comment]
@IncompletableFuture I merged this feature to `boot-data-mongo`, will fix it later. Thanks.
