### ISSUE TITLE
Request for interceptor example

### ISSUE THREAD

**Issue by roshangade** [hantsy/spring-reactive-sample#2]
Actually, this is not an issue. But, do you have any example or sample which provides guidance for request interceptors or middlewares in spring reactive? 
For example, 
- https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/servlet/config/annotation/WebMvcConfigurerAdapter.html
- http://sparkjava.com/documentation#filters
- http://expressjs.com/en/guide/using-middleware.html

Thanks.

**Comment by hantsy** [comment]
The reactive stack does not support the original MVC interceptor(Servlet based), but it support WebFilter. You can create a reactive [WebFilter](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/server/WebFilter.html) for yourself.

**Comment by roshangade** [comment]
That's great. Thank you so much. :+1:

**Comment by hantsy** [comment]
@roshangade Added a [WebFilter sample](https://github.com/hantsy/spring-reactive-sample/blob/master/web-filter/src/main/java/com/example/demo/SecurityWebFilter.java).

**Comment by roshangade** [comment]
:1st_place_medal: Awesome.
